### ISSUE TITLE
The temperature data looks cryptic.  

### ISSUE THREAD

**Issue by CallmeHongmaybe** [shelcia/Weather-app#116]
**Describe the bug**
The bug is a visual one - that is, the temperature data isn't clearly shown. 

**To Reproduce**
1. Click Germany card 
2. Click Show Weather Details button
3. Error is shown  

**Expected behavior**
The temperature should be in Celsius or Fahrenheit 

**Actual behavior**
Instead I see something like 289.62 &#176;F ( Which isn't telling if you ask me ) 

**Screenshots**
![Screen Shot 2022-06-12 at 11 21 16 AM](https://user-images.githubusercontent.com/44527246/173214325-58ae74aa-9a9b-41b7-80d1-f77f8d2d34ee.png)

**Comment by shelcia** [comment]
Thanks for noticing. It's fixed in latest build
