### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Pranav016** [shelcia/Weather-app#12]
I would like to add more info about the project such as technology used and add more tags in the README to beautify it.
Please assign me this issue.

**Comment by shelcia** [comment]
You could have made it one issue to add contributing guidelines, PR Template and code of conduct.

**Comment by Pranav016** [comment]
@shelcia Yes, I made separate issues because now the time I spend on this issue would be more than what I should be on an easy issue. Anyways, can you please make the tag 'intermediate' and assign this to me? Thanks 😄

**Comment by Kerveyfelix** [comment]
Can I work on this issue?
