### ISSUE TITLE
Light Theme doesn't look good. Need some customisation

### ISSUE THREAD

**Issue by Chaitanya31612** [shelcia/Weather-app#18]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
-The light theme makes the items excessively bright with an overlay. 

**Describe the solution you'd like**
-It can be made better with some style customisation.

**Additional context**

![image](https://user-images.githubusercontent.com/54992097/101522216-f0150680-39ac-11eb-8232-2bcdd1bb3ab2.png)

I would like to look upon it.

**Comment by shelcia** [comment]
Hey come up with solution then we can ahead . Like what you gonna change

**Comment by Chaitanya31612** [comment]
> Hey come up with solution then we can ahead . Like what you gonna change

I'll try to improve the UI for the light theme such that it doesn't look like having excessive white colour over all the elements but will try to make it look a bit more natural.

**Comment by Chaitanya31612** [comment]
Can you assign me this issue? @shelcia

**Comment by Chaitanya31612** [comment]
I've made a pull request @shelcia please review it and suggest changes if any.
