### ISSUE TITLE
Filter search list(searching countries) should be sort in alphabetically way(see more description below)

### ISSUE THREAD

**Issue by shelcia** [shelcia/Weather-app#2]
if user types in 'af' the search results should be the country name with the first two letters being 'af' not if 'af' is included anywhere in the country name

**Comment by tejaswini22199** [comment]
hey @shelcia  search results are being shown in that way only right

**Comment by shelcia** [comment]
> hey @shelcia  search results are being shown in that way only right 

The issues is being solved have to close it.
