### ISSUE TITLE
Feature request:show temperature in celcius/°C

### ISSUE THREAD

**Issue by PinRathod** [shelcia/Weather-app#27]
**Is your feature request related to a problem? Please describe.**
App shows temperature in Fahrenheit/°F. It may be showed by celcius/°C. add this feature request.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by Ashreejain** [comment]
I would love to work at this

**Comment by Ashreejain** [comment]
may you assign it to me
