### ISSUE TITLE
Search Results show one country less than actual results

### ISSUE THREAD

**Issue by Kashishjain04** [shelcia/Weather-app#4]
If there should be 3 results for a specific search, here only 2 of them are shown

**Comment by shelcia** [comment]
> If there should be 3 results for a specific search, here only 2 of them are shown

Search results are basically limited to top 5 matches and as of now we got 250 country data alone

**Comment by tejaswini22199** [comment]
hey @shelcia  did not understand the issue when we are entering we are getting more than 2 suggestions right? could you please elaborate

**Comment by Kashishjain04** [comment]
Basically search results are indexed from 1 to 5 so it will show from result number 2 to 6 but for the desired result indexing should be from 0 to 5

**Comment by Kashishjain04** [comment]
Anyways, i have fixed the issue

**Comment by shelcia** [comment]
The logic here is the top list match with the search input is displayed .. for more clarification do join https://discord.gg/TkKHAYVCza
