### ISSUE TITLE
Highlight Letters which match with search input in search results

### ISSUE THREAD

**Issue by shelcia** [shelcia/Weather-app#6]

**Comment by khushi0704** [comment]
Hey , can you assign me this task ? I am familiar with html , css but not java script so I haven't learnt reactjs yet , but I can try my best to learn in the least possible time and try to work on this issue ? So can you assign me this ?

**Comment by shelcia** [comment]
> Hey , can you assign me this task ? I am familiar with html , css but not java script so I haven't learnt reactjs yet , but I can try my best to learn in the least possible time and try to work on this issue ? So can you assign me this ?

Please join on discord. Will be sharing details over there

**Comment by khushi0704** [comment]
So can you assign me this task?

**Comment by Chaitanya31612** [comment]
Can I work on this feature @shelcia?

**Comment by Chaitanya31612** [comment]
@shelcia I've made a pull request adding this feature, please review it.
