### ISSUE TITLE
Implement search with country's capital names.

### ISSUE THREAD

**Issue by shelcia** [shelcia/Weather-app#7]

**Comment by dipscodehub** [comment]
I would love to work on this... Can you please assign the work to me

**Comment by tejaswini22199** [comment]
@shelcia  I also want to work on this issue can you assign me

**Comment by shelcia** [comment]
hey this doesn't work for both country name and capital

**Comment by Chaitanya31612** [comment]
@shelcia I'd like to work on this one.

**Comment by tejaswini22199** [comment]
so @shelcia  do we need to create two inputs one for capital and other for normal country

**Comment by shelcia** [comment]
Nope . You reassigned the country name with capital names and then you filtering out the results, that shouldn't be the case we need capital and country name and filter out the results. The major challenge here would be to redirect the capital name to its respective country page.

**Comment by rsrkpatwari1234** [comment]
Hello @shelcia I want to work on this. So if we input country name or the capital name, in both cases we should get directed to the country's page , Right ?? 
Please assign this issue to me as it is 27 days since it was last assigned.

**Comment by rsrkpatwari1234** [comment]
@shelcia , I have made a PR solving this issue.Please review it!!
