### ISSUE TITLE
bug: some cards are not rendering properly 

### ISSUE THREAD

**Issue by tusharnankani** [shelcia/Weather-app#8]
![bug](https://user-images.githubusercontent.com/61280281/100912939-1e02d280-34f7-11eb-814f-300549386e4c.gif)

I have not figured what reproduces this bug, but this issue can be addressed.

**Comment by shelcia** [comment]
Hey, I think it should be more like browser specific bug maybe. I use chrome on MacOS and it works just fine. To add the OS and browser so it could be more helpful

**Comment by tusharnankani** [comment]
Definitely a possibility.
I thought the same, tried testing the webpage using Chrome and Edge, as well. Was facing the same problem. Thought, it could be addressed.

**Comment by Chaitanya31612** [comment]
Yes, I also faced this issue. I would like to look upon it if it's available.

**Comment by tusharnankani** [comment]
I have not figured what reproduces this bug, but if @shelcia agrees, you can go ahead.

**Comment by Chaitanya31612** [comment]
> Yes, I also faced this issue. I would like to look upon it if it's available.

It is working fine in Mozilla firefox but having problem in chrome and edge.

**Comment by Chaitanya31612** [comment]
I've made a pull request and fixed the issue. @shelcia please review it.
